
name: Run Bot

on:
  push:
    branches:
      - master
  schedule:
    - cron: '40 0,2,4,6,8,10,12,14,16,18,20,22 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Run Bot
      run: |-
        python main.py
      env:
        MAPBOX_ACCESS_TOKEN: ${{secrets.MAPBOX_ACCESS_TOKEN}}
        CONSUMER_KEY: ${{secrets.CONSUMER_KEY}}
        CONSUMER_SECRET: ${{secrets.CONSUMER_SECRET}}
        ACCESS_TOKEN: ${{secrets.ACCESS_TOKEN}}
        ACCESS_TOKEN_SECRET: ${{secrets.ACCESS_TOKEN_SECRET}}

